import { useContext, useEffect, useState } from "react";
import Admin from "@/models/admin";
import showToast from "@/utils/toast";
import { safeJsonParse } from "@/utils/request";
import { LogoContext } from "@/LogoContext";

const defaultTemplate = {
  logo_position: "top-right",
  show_logo: true,
  show_page_numbers: true,
  footer_text: "Generated by RITA",
  primary_color: "#1f4e79",
  accent_color: "#4c78a8",
  chart_size: "large",
};

const logoPositions = [
  { label: "Top right", value: "top-right" },
  { label: "Top left", value: "top-left" },
  { label: "Bottom right", value: "bottom-right" },
  { label: "Bottom left", value: "bottom-left" },
  { label: "No logo", value: "none" },
];

const chartSizes = [
  { label: "Medium", value: "medium" },
  { label: "Large", value: "large" },
  { label: "Full width", value: "full" },
];

export default function RitaPdfTemplate() {
  const [template, setTemplate] = useState(defaultTemplate);
  const [hasChanges, setHasChanges] = useState(false);

  useEffect(() => {
    Admin.systemPreferencesByFields(["rita_pdf_template"]).then((res) => {
      const savedTemplate = res?.settings?.rita_pdf_template;
      setTemplate({
        ...defaultTemplate,
        ...(typeof savedTemplate === "string"
          ? safeJsonParse(savedTemplate, {})
          : savedTemplate || {}),
      });
    });
  }, []);

  function updateTemplate(key, value) {
    setTemplate((prev) => ({ ...prev, [key]: value }));
    setHasChanges(true);
  }

  async function handleSave(e) {
    e.preventDefault();
    const { success, error } = await Admin.updateSystemPreferences({
      rita_pdf_template: JSON.stringify(template),
    });

    if (!success) {
      showToast(`Failed to save RITA PDF template: ${error}`, "error");
      return;
    }

    showToast("RITA PDF template updated.", "success", { clear: true });
    setHasChanges(false);
  }

  return (
    <form
      className="flex flex-col gap-y-4 my-4 border-t border-white border-opacity-20 light:border-black/20 pt-6"
      onSubmit={handleSave}
    >
      <div>
        <p className="text-sm leading-6 font-semibold text-theme-text-primary">
          RITA chart PDF template
        </p>
        <p className="text-xs text-theme-text-secondary">
          Adjust the layout and styling RITA uses when it generates chart PDF
          reports.
        </p>
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-[minmax(0,520px)_320px] gap-6">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <SettingSelect
            label="Logo position"
            value={template.logo_position}
            options={logoPositions}
            onChange={(value) => updateTemplate("logo_position", value)}
          />
          <SettingSelect
            label="Chart size"
            value={template.chart_size}
            options={chartSizes}
            onChange={(value) => updateTemplate("chart_size", value)}
          />
          <ColorInput
            label="Primary color"
            value={template.primary_color}
            onChange={(value) => updateTemplate("primary_color", value)}
          />
          <ColorInput
            label="Accent color"
            value={template.accent_color}
            onChange={(value) => updateTemplate("accent_color", value)}
          />
          <label className="flex flex-col gap-y-2 md:col-span-2">
            <span className="text-sm font-medium text-theme-text-primary">
              Footer text
            </span>
            <input
              type="text"
              className="border border-white/10 light:border-slate-300 bg-theme-settings-input-bg text-theme-text-primary placeholder:text-theme-settings-input-placeholder text-sm rounded-lg focus:outline-primary-button active:outline-primary-button outline-none block w-full py-3 px-4"
              value={template.footer_text}
              maxLength={120}
              onChange={(e) => updateTemplate("footer_text", e.target.value)}
            />
          </label>
          <Toggle
            label="Show logo"
            checked={template.show_logo}
            onChange={(checked) => updateTemplate("show_logo", checked)}
          />
          <Toggle
            label="Show page numbers"
            checked={template.show_page_numbers}
            onChange={(checked) => updateTemplate("show_page_numbers", checked)}
          />
        </div>

        <PdfPreview template={template} />
      </div>

      {hasChanges && (
        <button
          type="submit"
          className="transition-all w-fit duration-300 border border-primary-button px-5 py-2.5 rounded-lg text-theme-text-primary text-sm items-center flex gap-x-2 hover:bg-primary-button hover:text-white focus:ring-gray-800"
        >
          Save PDF template
        </button>
      )}
    </form>
  );
}

function SettingSelect({ label, value, options, onChange }) {
  return (
    <label className="flex flex-col gap-y-2">
      <span className="text-sm font-medium text-theme-text-primary">
        {label}
      </span>
      <select
        className="cursor-pointer border border-white/10 light:border-slate-300 bg-theme-settings-input-bg text-theme-text-primary text-sm rounded-lg focus:outline-primary-button active:outline-primary-button outline-none block w-full py-3 px-4"
        value={value}
        onChange={(e) => onChange(e.target.value)}
      >
        {options.map((option) => (
          <option
            key={option.value}
            value={option.value}
            className="text-slate-900 bg-white"
          >
            {option.label}
          </option>
        ))}
      </select>
    </label>
  );
}

function ColorInput({ label, value, onChange }) {
  return (
    <label className="flex flex-col gap-y-2">
      <span className="text-sm font-medium text-theme-text-primary">
        {label}
      </span>
      <div className="flex items-center gap-x-3 border border-white/10 light:border-slate-300 bg-theme-settings-input-bg rounded-lg px-3 py-2">
        <input
          type="color"
          value={value}
          onChange={(e) => onChange(e.target.value)}
          className="h-8 w-10 bg-transparent border-none cursor-pointer"
        />
        <span className="text-sm text-theme-text-primary">{value}</span>
      </div>
    </label>
  );
}

function Toggle({ label, checked, onChange }) {
  return (
    <label className="flex items-center justify-between gap-x-3 rounded-lg border border-white/10 light:border-slate-300 bg-theme-settings-input-bg px-4 py-3 cursor-pointer">
      <span className="text-sm font-medium text-theme-text-primary">
        {label}
      </span>
      <input
        type="checkbox"
        checked={checked}
        onChange={(e) => onChange(e.target.checked)}
        className="h-4 w-4"
      />
    </label>
  );
}

function PdfPreview({ template }) {
  const { logo } = useContext(LogoContext);
  const showLogo = template.show_logo && template.logo_position !== "none";
  const logoClass = {
    "top-left": "top-4 left-4",
    "top-right": "top-4 right-4",
    "bottom-left": "bottom-4 left-4",
    "bottom-right": "bottom-4 right-4",
  }[template.logo_position];
  const chartHeight = {
    medium: "h-20",
    large: "h-28",
    full: "h-36",
  }[template.chart_size];

  return (
    <div className="rounded-lg border border-white/10 light:border-slate-300 bg-theme-settings-input-bg p-4">
      <p className="text-sm font-medium text-theme-text-primary mb-3">
        Preview
      </p>
      <div className="relative mx-auto h-[410px] w-[290px] bg-white rounded-sm shadow-lg overflow-hidden p-6">
        {showLogo && (
          <img
            src={logo}
            alt="RITA logo"
            className={`absolute ${logoClass} max-h-8 max-w-[72px] object-contain`}
          />
        )}
        <div
          className="h-4 w-40 rounded-sm mb-3"
          style={{ backgroundColor: template.primary_color }}
        />
        <div className="h-2 w-52 rounded-sm bg-slate-200 mb-2" />
        <div className="h-2 w-44 rounded-sm bg-slate-200 mb-6" />
        <div
          className={`${chartHeight} w-full rounded-sm flex items-end gap-x-2 p-3`}
          style={{ backgroundColor: `${template.accent_color}22` }}
        >
          {[42, 70, 55, 88, 62].map((height, index) => (
            <div
              key={index}
              className="flex-1 rounded-t-sm"
              style={{
                height: `${height}%`,
                backgroundColor:
                  index % 2 === 0
                    ? template.primary_color
                    : template.accent_color,
              }}
            />
          ))}
        </div>
        <div className="mt-5 h-2 w-56 rounded-sm bg-slate-200" />
        <div className="mt-2 h-2 w-48 rounded-sm bg-slate-200" />
        {template.footer_text && (
          <div className="absolute bottom-3 left-6 max-w-[180px] truncate text-[8px] text-slate-500">
            {template.footer_text}
          </div>
        )}
        {template.show_page_numbers && (
          <div className="absolute bottom-3 right-6 text-[8px] text-slate-500">
            1 / 3
          </div>
        )}
      </div>
    </div>
  );
}
